apiVersion: apps/v1
kind: Deployment
metadata:
  name: project-template-next-react
spec:
  template:
    spec:
      containers:
        - name: project-template-next-react
          env:
            - name: STAGE
              value: prod
            - name: SENTRY_DSN
              value: REPLACE_WITH_PROD_SENTRY_DSN
            - name: SENTRY_ENVIRONMENT
              value: prod
            - name: SENTRY_TRACES_SAMPLE_RATE
              value: "0.1"
