apiVersion: networking.istio.io/v1
kind: VirtualService
metadata:
  name: ceo-era
spec:
  gateways:
    - public-gateway
  http:
    - route:
        - destination:
            host: ceo-era
            port:
              number: 80
